### ISSUE TITLE
polyagamma issue

### ISSUE THREAD

**Issue by kaplans1** [pinellolab/CRISPR-millipede-target#2]
Hello,

When trying to install with "pip install crispr-millipede" I consistently get the issue "ModuleNotFoundError: No module named 'distutils.msvccompiler'

I've tried a handful of different python versions within virtual environments, as well as within a WSL system.

Looks like a cool tool, was hoping to try it out.

Thank You,
Sam

**Comment by doczmp** [comment]
Hi Sam,

Thank you for your interest in our tool. We have updated installation instructions in the read me. Could you try installing PyTorch first and then try installing the CRISPR-Millipede package with pip. Let me know if that works! 

Best,
Zain

**Comment by kaplans1** [comment]
Thank you - resolved!
